### ISSUE TITLE
SoftDeleteBehavior & Unit Testing = Error: Table users for model User was not found in datasource test.

### ISSUE THREAD

**Issue by ravage84** [CakeDC/utils#138] opened 2015-05-27 11:13 UTC
I ran into the following problem using the SoftDeleteBehavior:

When a model has an association with another one and you want to unit test one of them, you will run into an error message like:

> Error: Table users for model User was not found in datasource test.

I created a test app to showcase the problem:
https://github.com/ravage84/softdeletebbehavior-prob

Way to reproduce:
- Checkout repo
- Create DBs for default & test datasource
- Setup database config
- ``php console\cake.php schema create``
- ``php console\cake.php test app Model/Post --stderr``

Tested with CakePHP 2.6.1, 2.6.5, 2.5.8 & 2.4.10.using the dev-master of CakeDCs SoftDeleteBehavior or @dereuromark 's version at https://github.com/dereuromark/cakephp-tools/blob/2.5/Model/Behavior/SoftDeleteBehavior.php

The problem was already mentioned here:
https://github.com/dereuromark/cakephp-tools/issues/135

**Comment by ravage84** [comment] 2015-05-27 11:57
It does not matter if the behavior ist installed manually in the app or as Plugin (e.g. thorugh Composer).
Just checked.

**Comment by ravage84** [comment] 2015-05-27 11:58
If we remove the associatoins (in both associated models), the problem vanishes.

**Comment by ravage84** [comment] 2015-05-27 12:14
The problem seems to only appear i a ``$belongtsTo`` associatoin is set, such as ``Post $belongsTo User``
If there is only a ``$hasMany``, like ``User $hasMany Post``, it still works.

Here is the stack trace:

````
#0 CakePHP-App\lib\Cake\Model\Model.php(3644): Model->setSource('users')
#1 CakePHP-App\lib\Cake\Model\Model.php(1387): Model->getDataSource()
#2 CakePHP-App\lib\Cake\Model\Model.php(1483): Model->schema()
#3 CakePHP-App\app\Model\Behavior\SoftDeleteBehavior.php(54): Model->hasField('deleted')
#4 CakePHP-App\lib\Cake\Model\BehaviorCollection.php(145): SoftDeleteBehavior->setup(Object(User), Array)
#5 CakePHP-App\lib\Cake\Model\BehaviorCollection.php(66): BehaviorCollection->load('SoftDelete', Array)
#6 CakePHP-App\lib\Cake\Model\Model.php(774): BehaviorCollection->init('User', Array)
#7 [internal function]: Model->__construct(Array)
#8 CakePHP-App\lib\Cake\Utility\ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#9 CakePHP-App\lib\Cake\Model\Model.php(1077): ClassRegistry::init(Array)
#10 CakePHP-App\lib\Cake\Model\Model.php(886): Model->_constructLinkedModel('User', 'User', NULL)
#11 CakePHP-App\lib\Cake\Model\Model.php(919): Model->__isset('User')
#12 CakePHP-App\app\Model\Behavior\SoftDeleteBehavior.php(332): Model->__get('User')
#13 CakePHP-App\app\Model\Behavior\SoftDeleteBehavior.php(229): SoftDeleteBehavior->_softDeleteAssociations(Object(Post), true)
#14 CakePHP-App\app\Model\Behavior\SoftDeleteBehavior.php(66): SoftDeleteBehavior->softDelete(Object(Post), true)
#15 CakePHP-App\lib\Cake\Model\BehaviorCollection.php(145): SoftDeleteBehavior->setup(Object(Post), Array)
#16 CakePHP-App\lib\Cake\Model\BehaviorCollection.php(66): BehaviorCollection->load('SoftDelete', Array)
#17 CakePHP-App\lib\Cake\Model\Model.php(774): BehaviorCollection->init('Post', Array)
#18 CakePHP-App\lib\Cake\TestSuite\Fixture\CakeTestFixture.php(143): Model->__construct(NULL, NULL, 'default')
#19 CakePHP-App\lib\Cake\TestSuite\Fixture\CakeTestFixture.php(120): CakeTestFixture->init()
#20 CakePHP-App\lib\Cake\TestSuite\Fixture\CakeFixtureManager.php(163): CakeTestFixture->__construct()
#21 CakePHP-App\lib\Cake\TestSuite\Fixture\CakeFixtureManager.php(77): CakeFixtureManager->_loadFixtures(Array)
#22 CakePHP-App\lib\Cake\TestSuite\CakeTestRunner.php(57): CakeFixtureManager->fixturize(Object(PostTest))
#23 CakePHP-App\lib\Cake\TestSuite\CakeTestSuiteCommand.php(98): CakeTestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#24 CakePHP-App\lib\Cake\Console\Command\TestShell.php(274): CakeTestSuiteCommand->run(Array)
#25 CakePHP-App\lib\Cake\Console\Command\TestShell.php(317): TestShell->_run(Array, Array)
#26 CakePHP-App\lib\Cake\Console\Command\TestShell.php(256): TestShell->available()
#27 CakePHP-App\lib\Cake\Console\Shell.php(447): TestShell->main()
#28 CakePHP-App\lib\Cake\Console\ShellDispatcher.php(209): Shell->runCommand('app', Array)
#29 CakePHP-App\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#30 CakePHP-App\app\Console\cake.php(47): ShellDispatcher::run(Array)
#31 {main}
````

**Comment by omnuvito** [comment] 2015-06-04 21:12
Hi @ravage84,  I cloned your test app and I checked the problem you are considering, you have read the documentation for the SoftDelete behavior? I did the test in versions you named, setting SoftDelete behavior following step by step documentation, and I have not found to reproduce the same error. Let me know if using the documentation you still have the same problem.

**Comment by ravage84** [comment] 2015-06-04 22:10
@omnuvito  do you mean that bit of documentation at https://github.com/CakeDC/utils#softdelete-behavior ?
Yes I have read that. And now, I even added the two missing methods. But they didn't matter to the problem at hand. And yes the problem still exists.

**Comment by omnuvito** [comment] 2015-06-04 22:39
Yes, that documentation. @ravage84 can you rewrite the models? (baked again). With your test app, after I added the missing functions and cloned the Utils folder, I overwrote the models, fixtures and tests, I added again the testFoo() function, and the problem was solved.

**Comment by ravage84** [comment] 2015-06-04 22:57
You don't need to clone the Utils folder.
I copied the SoftDelete behavior file to the appropriate folder and this is a valid installation method.
I - and many others - do that when they don't want to include all those other utilities in plugins like Utils.

Please checkout my test app and don't do anything else than these steps:

- Checkout repo
- Create DBs for default & test datasource
- Setup database config
- php console\cake.php schema create
- php console\cake.php test app Model/Post --stderr

**Comment by ravage84** [comment] 2015-06-04 23:06
Also I assume your code works because you don't do import the fixtures from the model anymore as I do:
https://github.com/ravage84/softdeletebbehavior-prob/blob/6ea9b3f65d89f2a7e665931603ad7094d74bee24/app/Test/Fixture/PostFixture.php#L13

You probably chose a different option when you re-baked them...

**Comment by omnuvito** [comment] 2015-06-05 23:11
@ravage84 you're right, there is a problem with the import model in fixtures. I'm working on it, soon will be an update on the SoftDelete Behavior.

**Comment by CakeDC** [comment] 2015-06-22 14:32
Merged & fixed in develop, thank you!

**Closed by CakeDC** 2015-06-22 14:32 UTC
